<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLySinhVien" Class="StudentDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-UB8AMQ9;Initial Catalog=QuanLySinhVien;Integrated Security=True" SettingsObjectName="QLSV.Properties.Settings" SettingsPropertyName="QuanLySinhVienConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Diem" Member="Diems">
    <Type Name="Diem">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemQuaTrinhLan1" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DiemQuaTrinhLan2" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DiemCuoiKi" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="MonHoc_Diem" Member="MonHoc" ThisKey="MaMH" OtherKey="MaMH" Type="MonHoc" IsForeignKey="true" />
      <Association Name="SinhVien_Diem" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HeDT" Member="HeDTs">
    <Type Name="HeDT">
      <Column Name="MaHeDT" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHeDT" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="HeDT_Lop" Member="Lops" ThisKey="MaHeDT" OtherKey="MaHeDT" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.Khoa" Member="Khoas">
    <Type Name="Khoa">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Khoa_Lop" Member="Lops" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.KhoaHoc" Member="KhoaHocs">
    <Type Name="KhoaHoc">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KhoaHoc_Lop" Member="Lops" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Lop_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" />
      <Association Name="HeDT_Lop" Member="HeDT" ThisKey="MaHeDT" OtherKey="MaHeDT" Type="HeDT" IsForeignKey="true" />
      <Association Name="Khoa_Lop" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
      <Association Name="KhoaHoc_Lop" Member="KhoaHoc" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="KhoaHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="MaMH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTinChi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MonHoc_Diem" Member="Diems" ThisKey="MaMH" OtherKey="MaMH" Type="Diem" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="SinhVien_Diem" Member="Diems" ThisKey="MaSV" OtherKey="MaSV" Type="Diem" />
      <Association Name="Lop_SinhVien" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap" Member="DangNhaps">
    <Type Name="DangNhap">
      <Column Name="userName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="passWord" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.DSKhoa" Method="DSKhoa">
    <ElementType Name="DSKhoaResult">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Show_DSlop" Method="Show_DSlop">
    <ElementType Name="Show_DSlopResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Show_DSSinhVien" Method="Show_DSSinhVien">
    <ElementType Name="Show_DSSinhVienResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_SelectMaLop" Method="SinhVien_SelectMaLop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(10)" />
    <ElementType Name="SinhVien_SelectMaLopResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SuaDiemSinhVien" Method="SuaDiemSinhVien">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(15)" />
    <Parameter Name="HocKy" Parameter="hocKy" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiemQuaTrinhLan1" Parameter="diemQuaTrinhLan1" Type="System.Single" DbType="Real" />
    <Parameter Name="DiemQuaTrinhLan2" Parameter="diemQuaTrinhLan2" Type="System.Single" DbType="Real" />
    <Parameter Name="DiemCuoiKi" Parameter="diemCuoiKi" Type="System.Single" DbType="Real" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaKhoa" Method="SuaKhoa">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenKhoa" Parameter="tenKhoa" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DienThoai" Parameter="dienThoai" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaThongTinMonHoc" Method="SuaThongTinMonHoc">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenMH" Parameter="tenMH" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SoTinChi" Parameter="soTinChi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemDiemSinhVien" Method="ThemDiemSinhVien">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(15)" />
    <Parameter Name="HocKy" Parameter="hocKy" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiemQuaTrinhLan1" Parameter="diemQuaTrinhLan1" Type="System.Single" DbType="Real" />
    <Parameter Name="DiemQuaTrinhLan2" Parameter="diemQuaTrinhLan2" Type="System.Single" DbType="Real" />
    <Parameter Name="DiemCuoiKi" Parameter="diemCuoiKi" Type="System.Single" DbType="Real" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemKhoa" Method="ThemKhoa">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenKhoa" Parameter="tenKhoa" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DienThoai" Parameter="dienThoai" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemMoiSinhVien" Method="ThemMoiSinhVien">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="TenSV" Parameter="tenSV" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="QueQuan" Parameter="queQuan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="Char(20)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSinhVien" Method="UpdateSinhVien">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="TenSV" Parameter="tenSV" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="QueQuan" Parameter="queQuan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="Char(20)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemMonHoc" Method="ThemMonHoc">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenMH" Parameter="tenMH" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SoTinChi" Parameter="soTinChi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaDiemSinhVien" Method="XoaDiemSinhVien">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaKhoa" Method="XoaKhoa">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaMonHoc" Method="XoaMonHoc">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaSinhVien" Method="XoaSinhVien">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DSChuongtrinhDT" Method="DSChuongtrinhDT">
    <ElementType Name="DSChuongtrinhDTResult">
      <Column Name="MaHeDT" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenHeDT" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Show_DSMonhoc" Method="Show_DSMonhoc">
    <ElementType Name="Show_DSMonhocResult">
      <Column Name="MaMH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTinChi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Show_DSDiem" Method="Show_DSDiem">
    <ElementType Name="Show_DSDiemResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemQuaTrinhLan1" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DiemQuaTrinhLan2" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DiemCuoiKi" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SuaThongTinLop" Method="SuaThongTinLop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemThongTinLop" Method="ThemThongTinLop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaLop" Method="XoaLop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
</Database>